# Generated by Django 4.1.3 on 2024-05-02 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="content",
        ),
    ]
