# Generated by Django 4.1.3 on 2024-05-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_remove_article_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dest_dir",
                    models.CharField(
                        help_text="Default directory for exported articles.",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
