# Generated by Django 4.1.3 on 2024-05-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
