# Generated by Django 4.1.3 on 2024-06-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='teaser',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
