# Generated by Django 5.0.6 on 2024-06-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_article_teaser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
