# Generated by Django 5.0.6 on 2024-06-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_settings_options_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='site_name',
            field=models.CharField(default='', help_text='Site name', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
