# Generated by Django 5.0.6 on 2024-06-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_settings_site_name_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='site_headline',
            field=models.CharField(default='', help_text='Site headline', max_length=255),
        ),
    ]
